# Site settings
title: Zakrevskis.lt
description: > # this means to ignore newlines until "baseurl:"
  This blog not only about development.<br />
  My 7th try to write a blog. I will write mainly about development
  and I might add some personal stories. Mainly writing for myself.<br />
  Grammar nazi note: I'm not a native English speaker, but thanks
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.zakrevskis.lt" # the base hostname & protocol for your site
github_username:  arturasz
facebook_username:  arturas.zakrevskis
linkedin_username:  zakrevskis

# Build settings
markdown: kramdown
